# Generated by Django 4.2.4 on 2023-08-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_image_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('eid', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('cname', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=50)),
            ],
        ),
    ]
