# Generated by Django 4.2.4 on 2023-08-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_model',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='image_model',
            name='img',
            field=models.FileField(upload_to='djangoapp/static'),
        ),
    ]
