# Generated by Django 4.2.4 on 2023-08-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_alter_image_model_description_alter_image_model_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audionm', models.CharField(max_length=20)),
                ('aud', models.FileField(upload_to='djangoapp/static')),
                ('vdoname', models.CharField(max_length=20)),
                ('vdo', models.FileField(upload_to='djangoapp/staic')),
                ('pdfname', models.CharField(max_length=20)),
                ('pdf', models.FileField(upload_to='djangoapp/static')),
            ],
        ),
    ]
