# Generated by Django 4.2.4 on 2023-08-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_alter_fileupload_vdo'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('Kerala', 'KERALA'), ('Karnataka', 'KARNATAKA'), ('Tamilnadu', 'TAMILNADU')], max_length=30)),
                ('malay', models.BooleanField(default=False)),
                ('eng', models.BooleanField(default=False)),
                ('hindi', models.BooleanField(default=False)),
            ],
        ),
    ]
